@startuml
class com.medivault.entity.Medicines {
- int medicineId
- String medicineCode
- String medicineName
- String genericName
- String barcode
- String registrationNumber
- Integer categoryId
- Integer manufacturerId
- String unit
- Integer shelfId
- BigDecimal storageTempMin
- BigDecimal storageTempMax
- String storageConditions
- String dosage
- BigDecimal defaultDosageMin
- BigDecimal defaultDosageMax
- String dosageWarning
- int expiryAlertDays
- String contraindications
- boolean isPrescriptionRequired
- BigDecimal sellingPrice
- int minInventory
- boolean status
- LocalDateTime createdAt

+ int getMedicineId()
+ void setMedicineId(int)
+ String getMedicineCode()
+ void setMedicineCode(String)
+ String getMedicineName()
+ void setMedicineName(String)
+ String getGenericName()
+ void setGenericName(String)
+ String getBarcode()
+ void setBarcode(String)
+ String getRegistrationNumber()
+ void setRegistrationNumber(String)
+ Integer getCategoryId()
+ void setCategoryId(Integer)
+ Integer getManufacturerId()
+ void setManufacturerId(Integer)
+ String getUnit()
+ void setUnit(String)
+ Integer getShelfId()
+ void setShelfId(Integer)
+ BigDecimal getStorageTempMin()
+ void setStorageTempMin(BigDecimal)
+ BigDecimal getStorageTempMax()
+ void setStorageTempMax(BigDecimal)
+ String getStorageConditions()
+ void setStorageConditions(String)
+ String getDosage()
+ void setDosage(String)
+ BigDecimal getDefaultDosageMin()
+ void setDefaultDosageMin(BigDecimal)
+ BigDecimal getDefaultDosageMax()
+ void setDefaultDosageMax(BigDecimal)
+ String getDosageWarning()
+ void setDosageWarning(String)
+ int getExpiryAlertDays()
+ void setExpiryAlertDays(int)
+ String getContraindications()
+ void setContraindications(String)
+ boolean isPrescriptionRequired()
+ void setPrescriptionRequired(boolean)
+ BigDecimal getSellingPrice()
+ void setSellingPrice(BigDecimal)
+ int getMinInventory()
+ void setMinInventory(int)
+ boolean isStatus()
+ void setStatus(boolean)
+ LocalDateTime getCreatedAt()
+ void setCreatedAt(LocalDateTime)
}


@enduml